Lib / Update spring boot.
Fix proxy call error

```
java.lang.NullPointerException: Cannot invoke "jdk.internal.net.http.Http1Exchange$Http1RequestBodySubscriber.request(long)" because "this.bodySubscriber" is null
```